export const SEARCH_JOB = 'SEARCH_JOB';
export const SEARCH_JOB_REQUEST = 'SEARCH_JOB_REQUEST';

export const FETCH_JOBLISTS_REQUEST = 'FETCH_JOBLISTS_REQUEST';
export const FETCH_JOBLISTS_SUCCESS = 'FETCH_JOBLISTS_SUCCESS';
export const FETCH_JOBLISTS_FAILED = 'FETCH_JOBLISTS_FAILED';

export const PAGINATION_CHANGE_REQUEST = 'PAGINATION_CHANGE_REQUEST';
export const PAGINATION_CHANGE = 'PAGINATION_CHANGE';